-include .env

# Clean the repo
clean  :; forge clean


# Update Dependencies
update:; forge update
build:; forge build
compile:; forge compile
test :; forge test 
snapshot :; forge snapshot
format :; forge fmt